### ISSUE TITLE
removal of Provider: spec.controllerConfigRef had no effect for target provider pod

### ISSUE THREAD

**Issue by shanproofpoint** [crossplane-contrib/provider-upjet-gcp#236]
### What happened?
When removing  controllerConfigRef from Provider, the provider refuses to reflect the change to the target deployment.

say if we had the following controller config to allocate the provider-gcp to another node pool on gcp:
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: controller-installation-config
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: large-pool
  resources:
    requests:
      cpu: 10000m
      memory: 10Gi
```

and the provider-gcp references that controller config

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: dontcare
spec:
  package: xpkg.upbound.io/upbound/provider-gcp:v0.21.0
  controllerConfigRef:
    name: controller-installation-config
```

then the provider-gcp pod was confirmed to be relocated to the large-pool.

we then removed "controllerConfigRef" 

1. the provider refused to change the deployment for the provider-gcp pod. this is apparent from the fact that nodeSelector was still present in the deployment.
2. manually deleting the old deployment resulting in no new deployment being created
3. i went again and upgraded to xpkg.upbound.io/upbound/provider-gcp:v0.22.0 to trigger a reinstall and the issue was fixed. a new deployment was created without the nodeSelector.

### How can we reproduce it?
explained above

### What environment did it happen in?

* Universal Crossplane Version: 1.10.2
* Provider Version: xpkg.upbound.io/upbound/provider-gcp:v0.21.0
