### ISSUE TITLE
InstanceGroupManager forces targetSize to 3 despite yaml not setting it

### ISSUE THREAD

**Issue by shanproofpoint** [crossplane-contrib/provider-upjet-gcp#282]
### What happened?
```
        apiVersion: compute.gcp.upbound.io/v1beta1
        kind: InstanceGroupManager
        metadata:
          name: my-igm
        spec:
          forProvider:
            namedPort:
              - name: bird-port
                port: 8888
              - name: goose-port
                port: 8443
              - name: coredns-port
                port: 53
            baseInstanceName: my
            zone: us-central1-a
            #targetSize: 3
            version:
              - instanceTemplateRef:
                  name: my-template
                name: primary
            #        targetSize:
            #          - percent: 100
            updatePolicy:
              - type: PROACTIVE
                minimalAction: REPLACE
                mostDisruptiveAllowedAction: REPLACE
                #maxSurgePercent: 20
                maxUnavailableFixed: 3
                #minReadySec: 50
                #replacementMethod: RECREATE

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Autoscaler
metadata:
    name: my-igm-autoscaler
spec:
    deletionPolicy: Delete
    forProvider:
        autoscalingPolicy:
            - cooldownPeriod: 60
              loadBalancingUtilization:
                - target: 0.8
              maxReplicas: 18
              minReplicas: 3
        project: my-project
        target: .../my-igm
        targetRef:
            name: pfpt-pop-dev-gcp-europe-west3-clown1-igm
        zone: europe-west3-a
    providerConfigRef:
        name: default


```

This still results in an igm with targetSize 3... despite it not being in the yaml.
and it is interfering with the autoscaling. autoscaler wants to bring in more instances, and this object via terraform wants to set it back to 3 (as confirmed through gke logs).  very frustrating. how do we force igm to not set the targetSize and not fight autoscaling?

### How can we reproduce it?
see above

### What environment did it happen in?

* Crossplane Version: crossplane 1.10.2
* Provider Version: xpkg.upbound.io/upbound/provider-gcp:v0.21.0
* Kubernetes Version: v1.24.9-gke.3200
* Kubernetes Distribution: GKE
