### ISSUE TITLE
SSLCert Resource Never Syncs

### ISSUE THREAD

**Issue by bradkwadsworth-mw** [crossplane-contrib/provider-upjet-gcp#304]
### What happened?
The `sslcerts.sql.gcp.upbound.io` resource always seems to fail with the following error.
```
managed/sql.gcp.upbound.io/v1beta1, kind=sslcert  cannot get a terraform workspace for resource: cannot get id: project: no such field
```

### How can we reproduce it?
Apply a sslcerts.sql.gcp.upbound.io manifest.

### What environment did it happen in?

* Crossplane Version: v1.12.1
* Provider Version: v0.32.0
* Kubernetes Version: v1.26.4
* Kubernetes Distribution: KIND

**Comment by turkenf** [comment]
Hi @bradkwadsworth-mw,

Thank you for raising this issue, it can be reproduced with the following example:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: SSLCert
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Depends on SQL instance to be successfully deleted"
    meta.upbound.io/example-id: sql/v1beta1/sslcert
  labels:
    testing.upbound.io/example-name: example_cert
  name: example-cert
spec:
  forProvider:
    commonName: client-name
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: example_instance
  writeConnectionSecretToRef:
    name: example-sql-ssl-secret
    namespace: upbound-system

---

apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/databaseinstance
  labels:
    testing.upbound.io/example-name: example_instance
  name: example-instance-test5
spec:
  forProvider:
    region: "us-central1"
    databaseVersion: "MYSQL_5_7"
    settings:
      - tier: "db-f1-micro"
        diskSize: 20
    deletionProtection: false 
  writeConnectionSecretToRef:
    name: example-sql-db-instance-secret
    namespace: upbound-system
```
