### ISSUE TITLE
event arc  cannot refer the v2 version of cloud run

### ISSUE THREAD

**Issue by bhismnarayan** [crossplane-contrib/provider-upjet-gcp#313]
When using event arc to refer to v2 version of cloud run the provider by default tries to find v1 version of cloud run
Here is the composition used
```
- name: eventarc-trigger
      base:
        apiVersion: eventarc.gcp.upbound.io/v1beta1
        kind: Trigger
        metadata:
          name: #patch-me
        spec:
          forProvider:
            serviceAccount: #patch-me
            destination:
              - cloudRunService:
                  - region: #patch-me
                    serviceRef:
                      name: #patchme
            location: #patch-me
            matchingCriteria:
              - attribute: type
                value: google.cloud.pubsub.topic.v1.messagePublished
          providerConfigRef:
            name: default      
      patches:
        - fromFieldPath: spec.claimRef.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.destination[0].cloudRunService[0].region
        - fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.destination[0].cloudRunService[0].serviceRef.name
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.location
        - fromFieldPath: status.eventarcTrigger.serviceAccount
          toFieldPath: spec.forProvider.template[0].spec[0].serviceAccountName
          policy:
            fromFieldPath: Required
```

Below is the error 
```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-06-01T10:16:05Z
    Message:               cannot resolve references: mg.Spec.ForProvider.Destination[i3].CloudRunService[i4].Service: cannot get referenced resource: Service.cloudrun.gcp.upbound.io "example-cloudrun09" not found
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                           Age               From                                                   Message
  ----     ------                           ----              ----                                                   -------
  Warning  CannotResolveResourceReferences  1s (x7 over 62s)  managed/eventarc.gcp.upbound.io/v1beta1, kind=trigger  cannot resolve references: mg.Spec.ForProvider.Destination[i3].CloudRunService[i4].Service: cannot get referenced resource: Service.cloudrun.gcp.upbound.io "example-cloudrun09" not found
```

I think we need a way where we refer to v2 version of cloud run as well
