### ISSUE TITLE
New mapping for legacy BucketPolicy object

### ISSUE THREAD

**Issue by Demonsthere** [crossplane-contrib/provider-upjet-gcp#385]
### What happened?
Hello there! 
I am in the middle of migrating the old monlith provider to the new version, and could not find a proper translation/new version for the legacy BucketPolicy object. 
The gcp-storage provider has multiple objects https://marketplace.upbound.io/providers/upbound/provider-gcp-storage/v0.36.0 but i cannot find anything that would be a one to one replacement for the following manifest

```yaml
# Source: resources/charts/owc/templates/gcs-bucket-policy-backoffice.yaml
apiVersion: storage.gcp.crossplane.io/v1alpha1
kind: BucketPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: test-bucket-policy
  namespace: crossplane-system
spec:
  deletionPolicy: Delete
  forProvider:
    bucket: test-bucket
    policy:
      bindings:
        - role: roles/storage.legacyObjectReader
          members:
            - allUsers
        - role: roles/storage.objectViewer
          members:
            - serviceAccount:redacted
        - role: roles/storage.legacyBucketOwner
          members:
            - serviceAccount:redacted
            - domain:redacted
        - role: roles/storage.legacyObjectOwner
          members:
            - serviceAccount:redacted
            - domain:redacted
        - role: roles/storage.objectAdmin
          members:
            - serviceAccount:redacted
            - domain:redacted
        - role: roles/storage.objectCreator
          members:
            - serviceAccount:redacted
            - domain:redacted
```

Could you please point me in the right direction, what would be the proper CR to migrate this policy to?

### What environment did it happen in?

* Crossplane Version:
* Provider Version:
* Kubernetes Version:  
* Kubernetes Distribution:
