### ISSUE TITLE
DatabaseInstance Replica configuration Required for Non-MySQL Instances

### ISSUE THREAD

**Issue by snelsondexcom** [crossplane-contrib/provider-upjet-gcp#413]
### What happened?

_NOTE: The previous issue was closed because it referenced an older version: https://github.com/upbound/provider-gcp/issues/379. Opening this new issue now that we're also seeing it with `v0.37.0`._

Per the docs, `replicaConfiguration` should only be applicable to MySQL instances:
> Valid only for MySQL instances

I was able to create a read replica for a PostgreSQL CloudSQL instance using the `DatabaseInstance` resource but it failed to sync with the following error:
```
Missing required argument: \"replica_configuration.0.client_certificate\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.dump_file_path\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.master_heartbeat_period\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.ssl_cipher\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.username\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.verify_server_certificate\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.ca_certificate\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.client_key\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.connect_retry_interval\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.failover_target\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified
Missing required argument: \"replica_configuration.0.password\": one of `replica_configuration.0.ca_certificate,replica_configuration.0.client_certificate,replica_configuration.0.client_key,replica_configuration.0.connect_retry_interval,replica_configuration.0.dump_file_path,replica_configuration.0.failover_target,replica_configuration.0.master_heartbeat_period,replica_configuration.0.password,replica_configuration.0.ssl_cipher,replica_configuration.0.username,replica_configuration.0.verify_server_certificate` must be specified"
```
Workaround to get the refresh to succeed -- provide an "empty" replica config, e.g.
```
    replicaConfiguration:
    - clientCertificate: ""
      clientKey: ""
      connectRetryInterval: 0
      dumpFilePath: ""
      failoverTarget: false
      masterHeartbeatPeriod: 0
      sslCipher: ""
      username: ""
      verifyServerCertificate: false
```

### How can we reproduce it?

Create a replica instance (`DatabaseInstance` with `masterInstanceName` defined) for a PostgreSQL CloudSQL instance but omit a `replicaConfiguration`.

### What environment did it happen in?

* Crossplane Version: v1.13.2
* Provider Version: v0.37.0
* Kubernetes Version: v1.24.14
* Kubernetes Distribution: GKE

**Comment by snelsondexcom** [comment]
Sure thing! I added manifests below.

To reiterate, I am able to _create_ primary and read replica instances using the manifests but the read replica fails to _sync_ after it's created. So any additional changes to the `test-replica` manifest after the initial creation do not take effect.

Primary:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: test-primary
spec:
  forProvider:
    databaseVersion: POSTGRES_15
    project: REDACTED
    region: us-central1
    settings:
    - availabilityType: ZONAL
      edition: ENTERPRISE
      tier: db-custom-1-4096
  providerConfigRef:
    name: gcp-provider
```

Replica:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: test-replica
spec:
  forProvider:
    databaseVersion: POSTGRES_15
    masterInstanceName: test-primary
    project: REDACTED
    region: us-central1
    settings:
    - availabilityType: ZONAL
      edition: ENTERPRISE
      tier: db-custom-1-4096
  providerConfigRef:
    name: gcp-provider
```

Wait for primary and replica creation, then modify the replica... e.g. add a db flag:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: test-replica
spec:
  forProvider:
    databaseVersion: POSTGRES_15
    masterInstanceName: test-primary
    project: REDACTED
    region: us-central1
    settings:
    - availabilityType: ZONAL
      databaseFlags:
      - name: cloudsql.enable_pgaudit
        value: "on"
      edition: ENTERPRISE
      tier: db-custom-1-4096
  providerConfigRef:
    name: gcp-provider
```

The replica change does not take effect unless an "empty" `replicaConfiguration` is provided:
```
    replicaConfiguration:
    - clientCertificate: ""
      clientKey: ""
      connectRetryInterval: 0
      dumpFilePath: ""
      failoverTarget: false
      masterHeartbeatPeriod: 0
      sslCipher: ""
      username: ""
      verifyServerCertificate: false
```

**Comment by snelsondexcom** [comment]
@turkenf ☝️

**Comment by turkenf** [comment]
@snelsondexcom, thank you for your response.

Unless I'm missing something, I can't reproduce the error in `v0.41.0` with the steps below.
- I created the following:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: test-primary
spec:
  forProvider:
    databaseVersion: POSTGRES_15
    region: us-central1
    settings:
    - availabilityType: ZONAL
      edition: ENTERPRISE
      tier: db-custom-1-4096
```
- Waited for the primary resource ready and created the following:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: test-replica
spec:
  forProvider:
    databaseVersion: POSTGRES_15
    masterInstanceName: test-primary
    region: us-central1
    settings:
    - availabilityType: ZONAL
      edition: ENTERPRISE
      tier: db-custom-1-4096
```
- Then, edited the replica by adding `databaseFlags` and I did not encounter any issues:
```
> k get databaseinstance.sql.gcp.upbound.io/test-replica -o yaml -w
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
...
..
.
spec:
  deletionPolicy: Delete
  forProvider:
    databaseVersion: POSTGRES_15
    deletionProtection: true
    masterInstanceName: test-primary
    project: official-provider-testing
    region: us-central1
    replicaConfiguration:
    - {}
    settings:
    - availabilityType: ZONAL
      databaseFlags:
      - name: cloudsql.enable_pgaudit
        value: "on"
      edition: ENTERPRISE
      tier: db-custom-1-4096
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  <redacted>
...
..
.
  conditions:
  - lastTransitionTime: "2024-01-18T12:56:11Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-01-18T12:51:14Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-01-18T13:03:51Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
  - lastTransitionTime: "2024-01-18T13:00:44Z"
    reason: UpToDate
    status: "True"
    type: Test
```

Could you please try provider version `0.41.0` and let us know?
