### ISSUE TITLE
[provider-Redis] writeConnectionSecretToRef doesn't publish server CA certs

### ISSUE THREAD

**Issue by snelsondexcom** [crossplane-contrib/provider-upjet-gcp#429]
### What happened?
For **instances.redis.gcp.upbound.io**, `writeConnectionSecretToRef` publishes the host and auth string only. It does _not_ publish `serverCaCerts` (which are exposed as part of the instance resource's `status`).

Similar to https://github.com/upbound/provider-gcp/issues/387, we can't currently automate Redis instance creation (and connections) without this addition.

### How can we reproduce it?
Create a redis instance with `writeConnectionSecretToRef`, e.g.
```
apiVersion: redis.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: redis-test
spec:
  providerConfigRef:
    name: unbound-provider-config-gcp
  forProvider:
    authEnabled: true
    memorySizeGb: 1
    region: europe-west1
    tier: BASIC
    redisVersion: REDIS_7_0
  writeConnectionSecretToRef:
    namespace: test
    name: redis-test
```

### What environment did it happen in?

* Crossplane Version: v1.13.2
* Provider Version: v0.39.0
* Kubernetes Version: v1.25.12
* Kubernetes Distribution: GKE
