### ISSUE TITLE
Is there a way to reference ServiceAccounts by kubernetes resource name?

### ISSUE THREAD

**Issue by jenshornan** [crossplane-contrib/provider-upjet-gcp#448]
### What problem are you facing?

I want to referens the ServiceAccount:
```
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    crossplane.io/external-name: test-cross
  labels:
    testing.upbound.io/example-name: weecross
  name: testa-cross
spec:
  forProvider:
    displayName: Crossplane Example Service Account
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: test-crossproject-iam-member
spec:
  forProvider:
    member: 
       fromref: testa-cross
    project: xxxx
    role: roles/run.invoker
```

It would be nice to be able to reference the serviceAccount based on the name of the kubernetes resource. As shown in the above example. Maybe this is already possible?
