### ISSUE TITLE
[Bug]: Use existing ServiceAccount 

### ISSUE THREAD

**Issue by gabriel-suela** [crossplane-contrib/provider-upjet-gcp#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps to Reproduce

```
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: airflow.xxxx.xxxx
  annotations:
    crossplane.io/external-name: airflow.xxxx.xxxx
spec:
  deletionPolicy: Orphan
  forProvider: {}
```

### What happened?

I want to claim an existing ServiceAccount in my argo cd, im currently importing my existing resources using the annotation
`crossplane.io/external-name: resource-name`. But in a service account context, i can't import by using SA name, or SA email. Can someone show me how to do it? i cannot figure that out by just looking at the examples

### Crossplane Version

1.15.2

### Provider Version

v1.2.0
