### ISSUE TITLE
[Bug]: MySQL Root user is removed upon initial creation of the instance

### ISSUE THREAD

**Issue by deleocj** [crossplane-contrib/provider-upjet-gcp#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

databaseinstance.sql.gcp.upbound.io MySQL

### Steps to Reproduce

Applying the yaml file for a CloudSQL MySQL:
```
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/databaseinstance
  labels:
    testing.upbound.io/example-name: example_instance
  name: cj-test-mysql-new2
spec:
  forProvider:
    databaseVersion: MYSQL_8_0
    deletionProtection: false
    region: us-central1
    settings:
      - ipConfiguration:
        - requireSsl: false
          ipv4Enabled: false
          privateNetwork: <NETWORK>
        diskSize: 20
        tier: db-perf-optimized-N-64
        userLabels:
          snow: my-snow
          beans: mybeans
        edition: ENTERPRISE_PLUS
        databaseFlags:
          - name: cloudsql_iam_authentication
            value: "on"
  writeConnectionSecretToRef:
    name: upbound-cj-sql-db-instance-secret
    namespace: upbound-system
```

### What happened?

The instance is provisioned with the root user, then immediately after the instance finished creating the root user is dropped. My code relies on the root credentials to connect to the instance

### Crossplane Version

1.15.2

### Provider Version

1.1.0
