### ISSUE TITLE
[Bug]: **Critical issue**: When a provider is removed, external resources are also deleted.

### ISSUE THREAD

**Issue by roldyxoriginal** [crossplane-contrib/provider-upjet-gcp#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

All resources were affected, *.*.gcp.upbound.io/v1beta1.

### Resource MRs required to reproduce the bug
```
apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  name: roldyx
spec:
  deletionPolicy: Delete
  forProvider:
    addressType: EXTERNAL
    description: eliminar
    project: xxxxxxx
  managementPolicies:
  - '*'
  providerConfigRef:
    name: crossplane-loadbalancer-creds

```
### Steps to Reproduce

I create any resource. (Ex: globaladdress)
I delete the provider. (Ex: provider-gcp-compute)
Here more details.. [link](https://github.com/crossplane/crossplane/issues/4251#issuecomment-2158590566)

### What happened?

As soon as the provider is deleted, the external resource is also deleted. This does not happen with resources created in Kubernetes.
Then I redeploy the provider, and obviously it's Healthy=False. I fix the CRD, and all resources disappear, so I have to redeploy everything again.
If the deletionPolicy is Orphan, we avoid the headache of losing all remote resources. But we clearly have to redeploy everything again.

### Crossplane Version

v1.14.4

### Provider Version

v0.41.0 v0.41.4 c1.2.0  all these version were tested

### Kubernetes Version

v1.27.3

### Kubernetes Distribution

GKE
