### ISSUE TITLE
[Bug]: singleton lists as embedded objects conversion fails in case of `Cluster.spec.forProvider.addonsConfig`

### ISSUE THREAD

**Issue by girdharshubham** [crossplane-contrib/provider-upjet-gcp#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

* container.gcp.upbound.io/v1beta2 - Cluster
* container.gcp.upbound.io/v1beta1 - Cluster

### Resource MRs required to reproduce the bug
```
-           apiVersion: container.gcp.upbound.io/v1beta1
+          apiVersion: container.gcp.upbound.io/v1beta2
            kind: Cluster
...
                addonsConfig:
-                - httpLoadBalancing:
-                  - disabled: {{ $.observed.composite.resource.spec.disableHttpLoadBalancing }}
-                - networkPolicyConfig:
-                  - disabled: {{ not $.observed.composite.resource.spec.networkPolicy.enabled }}
+                  httpLoadBalancing:
+                    disabled: {{ $.observed.composite.resource.spec.disableHttpLoadBalancing }}
+                  networkPolicyConfig:
+                   disabled: {{ not $.observed.composite.resource.spec.networkPolicy.enabled }}
```
### Steps to Reproduce

1. Create v1beta1 cluster with addon configurations for load balancing and network policy config (or multiple addon configurations)
2. Bump to 1.2.0/1.3.0
3. kubectl get cluster
```
Error from server: conversion webhook for container.gcp.upbound.io/v1beta1, Kind=Cluster failed: cannot convert from the spoke version "v1beta1" to the hub version "v1beta2": cannot apply the PavedConversion for the "google_container_cluster" object: failed to convert the source map in mode "toEmbeddedObject" with source API version "v1beta1", target API version "v1beta2": singleton list, at the field path addonsConfig, must have a length of at most 1 but it has a length of 2
```

### What happened?

Cronjob pods and replicaset pods stopped getting garbage collected on the cluster which prompted me to check api server logs. I found the conversion webhook failing. Release notes don't really specify it as a breaking change. 🤔 

### Crossplane Version

1.16

### Provider Version

1.3.0

### Kubernetes Version

1.27

### Kubernetes Distribution

GKE

**Comment by turkenf** [comment]
Hi @girdharshubham,

Thank you for raising this issue, I cannot reproduce the issue in the Kind cluster with the information given. I'm using the following basic example:
```
apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    location: europe-north1
    ipAllocationPolicy:
      - {}
    enableAutopilot: true
    enableIntranodeVisibility: true
    deletionProtection: false
```
Can you please provide us with the full example you used?

**Comment by girdharshubham** [comment]
I think it happens when you try to provide addonsConfig with more than one addon.

**Comment by turkenf** [comment]
> I think it happens when you try to provide addonsConfig with more than one addon.

Could you please provide us with the full example you used?

**Comment by archae0pteryx** [comment]
I have the same issue. Here is my full example with the addonsConfig included:
```

**Comment by mergenci** [comment]
[Marketplace documentation](https://marketplace.upbound.io/providers/upbound/provider-gcp-container/v1.7.0/resources/container.gcp.upbound.io/Cluster/v1beta1) for `addonsConfig` (v1beta1) is a little bit confusing. When I check the field's Terraform schema, I can see that [it's a singleton list](https://github.com/hashicorp/terraform-provider-google/blob/v5.39.0/google/services/container/resource_container_cluster.go#L288-L292). Therefore, I assume that the manifest should look like the following, in which `addonsConfig` is a list of one object:

```
spec:
  forProvider:
    addonsConfig:
    - gcePersistentDiskCsiDriverConfig:
      - enabled: true
      gcsFuseCsiDriverConfig:
      - enabled: true
      httpLoadBalancing:
      - disabled: false
```

PS: Provider is using v1beta1 as storage version. It supports v1beta2 using conversion functions.
