### ISSUE TITLE
[Bug]: CloudSQL Provider database iam auth users cannot be created

### ISSUE THREAD

**Issue by codergolem** [crossplane-contrib/provider-upjet-gcp#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

sql.gcp.upbound.io/v1beta1 - User

### Resource MRs required to reproduce the bug

apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: somename@gcp-projectid.iam.gserviceaccount.com
spec:
  forProvider:
    instanceRef:
      name: InstanceName
    type: CLOUD_IAM_SERVICE_ACCOUNT
    project: gcp-projectid
  providerConfigRef:
    name: default

### Steps to Reproduce

Try to create a cloudsql user of the type CLOUD_IAM_SERVICE_ACCOUNT or CLOUD_IAM_USER using the User resource. The name for the user is passed as the resource name, but given the user name for these user types are email addresses the name isnt compatible with K8s resource names rules (invalid characters), so it cannot be created. Additionally you cannot have two users with the same name but on different instances as you would end up having two k8s resources with the same name. 
The solution would be to provide a field other than the resource name to pass the user name, as in the original terraform resource.

### What happened?

Resource cannot be created

### Crossplane Version

 1.12.1

### Provider Version

1.5.0

**Comment by turkenf** [comment]
You can use `crossplane.io/external-name` annotation:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: test
  annotations:
    crossplane.io/external-name: somename@gcp-projectid.iam.gserviceaccount.com
spec:
  forProvider:
    instanceRef:
      name: InstanceName
    type: CLOUD_IAM_SERVICE_ACCOUNT
    project: gcp-projectid
  providerConfigRef:
    name: default
```
