### ISSUE TITLE
[Bug]: Matching by selector doesn't work for some resources

### ISSUE THREAD

**Issue by Bluesboy** [crossplane-contrib/provider-upjet-gcp#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

compute.gcp.upbound.io/v1beta2 - BackendService
compute.gcp.upbound.io/v1beta2 - URLMap
compute.gcp.upbound.io/v1beta2 - GlobalForwardingRule

### Resource MRs required to reproduce the bug

Backend Service manifest:
```
apiVersion: compute.gcp.upbound.io/v1beta2
kind: BackendService
metadata:
  name: example-backend-service
  labels:
    example-label: test-selector
spec:
  forProvider:
    loadBalancingScheme: EXTERNAL_MANAGED
```

URLMap manifest:
```
apiVersion: compute.gcp.upbound.io/v1beta2
kind: URLMap
metadata:
  name: example-url-map
  labels:
    example-label: test-selector
spec:
  forProvider:
    defaultServiceSelector:
      matchLabels:
        example-label: test-selector
```

### Steps to Reproduce

Create BackendService resource, refer it in URLMap resource and apply it.

### What happened?

ReconcileError in URLMap resourse

### Relevant Error Output Snippet

```shell
cannot resolve references: mg.Spec.ForProvider.DefaultService: no resources matched selector
```

### Crossplane Version

1.16.0

### Provider Version

1.5.0

### Kubernetes Version

v1.30.1-gke.1329003

### Kubernetes Distribution

GKE

### Additional Info

Same thing happening with `GlobalForwardingRule`, if I refer by selector to `TargetHTTPProxy` with `targetSelector`, however `ipAddressSelector` works fine.

If I'm trying to refer to the `BackendService` with `defaultServiceRef`, resource give me
```cannot resolve references: mg.Spec.ForProvider.DefaultService: cannot get referenced resource: BackendBucket.compute.gcp.upbound.io "example-backend-service" not found```
