### ISSUE TITLE
upbound sslcertificate resource tries to recreate even with external-name annotation

### ISSUE THREAD

**Issue by shanproofpoint** [crossplane-contrib/provider-upjet-gcp#59]
We found this problem while moving from crossplane jet gcp provider to upbound gcp provider:

**old:**
```yaml
apiVersion: compute.gcp.jet.crossplane.io/v1alpha1
kind: SSLCertificate
metadata:
  name: my-ssl-cert-2
spec:
  forProvider:
    name: my-ssl-cert-2
    certificateSecretRef:
      name: tls-wildcard-crt
      key: tls.crt
      namespace: mynamespace
    privateKeySecretRef:
      name: tls-wildcard-crt
      key: tls.key
      namespace: mynamespace
```

**new:**
```yaml
apiVersion: compute.gcp.upbound.io/v1beta1
kind: SSLCertificate
metadata:
  name: my-ssl-cert-2
  annotations:
    crossplane.io/external-name: my-ssl-cert-2
spec:
  forProvider:
    #name: my-ssl-cert-2
    certificateSecretRef:
      name: tls-wildcard-crt
      key: tls.crt
      namespace: mynamespace
    privateKeySecretRef:
      name: tls-wildcard-crt
      key: tls.key
      namespace: mynamespace
```

### What happened?
We are expecting that the ssl certificate does not recreate and the status data would just populate given that the 
crossplane.io/external-name: my-ssl-cert-2 was specified in the annotations of the new version.

### How can we reproduce it?
yaml included

### What environment did it happen in?
* Universal Crossplane Version:
not using uxp

* Provider Version:
**old:**
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-jet-gcp
spec:
  package: crossplane/provider-jet-gcp:v0.2.0-preview
```

**new:**
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-upbound-gcp
spec:
  package: xpkg.upbound.io/upbound/provider-gcp:v0.18.0
```
