### ISSUE TITLE
[Bug]: AlloyDB cluster/instance do not populate writeConnectionSecretToRef secret

### ISSUE THREAD

**Issue by drewwells** [crossplane-contrib/provider-upjet-gcp#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Resource MRs required to reproduce the bug

```
apiVersion: alloydb.gcp.upbound.io/v1beta2
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: alloydb/v1beta1/instance
  labels:
    testing.upbound.io/example-name: alloydb-test
  name: alloydb-test
spec:
  providerConfigRef:
    name: dwells
  writeConnectionSecretToRef:
    name: alloydb-creds-cluster
    namespace: dwells
  forProvider:
    location: us-central1
---
apiVersion: alloydb.gcp.upbound.io/v1beta2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: alloydb/v1beta2/instance
  labels:
    testing.upbound.io/example-name: alloydb-test
  name: alloydb-test
spec:
  providerConfigRef:
    name: dwells
  writeConnectionSecretToRef:
    name: alloydb-creds-instance
    namespace: dwells
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: alloydb-test
    instanceType: PRIMARY
    machineConfig:
      cpuCount: 2
```      

### Steps to Reproduce

kubectl apply -f {yaml from above}

Notice that cluster and instance are created in GCP
A user is created in postgres `alloydbsuperuser`
List the secrets and they are empty

```
❯ k -n dwells get secret                                                
NAME                                                        TYPE                                DATA   AGE
alloydb-creds-cluster                                       connection.crossplane.io/v1alpha1   0      6m7s
alloydb-creds-instance                                      connection.crossplane.io/v1alpha1   0      6m7s
```

### What happened?

I expect that the secrets are created with hostname, user, and password as mentioned in the documentation.

### Crossplane Version

1.16.0

### Provider Version

1.6.0

### Kubernetes Version

v1.25.4

### Kubernetes Distribution

GKE
