### ISSUE TITLE
[Bug]: DatabaseInstance.sql enters the update loop with PostgreSQL server

### ISSUE THREAD

**Issue by turkenf** [crossplane-contrib/provider-upjet-gcp#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

sql.gcp.upbound.io/v1beta1 - DatabaseInstance

### Resource MRs required to reproduce the bug

```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  labels:
    testing.upbound.io/example-name: instance-con
  name: example-ins-fttest3
spec:
  forProvider:
    databaseVersion: POSTGRES_15
    deletionProtection: false
    region: us-central1
    settings:
    - tier: "db-f1-micro"
```

### Steps to Reproduce

Install the providers and apply the above manifest.

### What happened?

After the resource is created, diff is detected and enters the update loop.

### Relevant Error Output Snippet

```shell
2024-08-05T20:41:18Z	DEBUG	provider-gcp	Diff detected	{"uid": "f111f457-327b-4dae-b517-43a96d82f978", "name": "example-ins-fttest3", "gvk": "sql.gcp.upbound.io/v1beta1, Kind=DatabaseInstance", "instanceDiff": "*terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{\"settings.0.insights_config.#\":*terraform.ResourceAttrDiff{Old:\"1\", New:\"0\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, \"settings.0.insights_config.0.query_string_length\":*terraform.ResourceAttrDiff{Old:\"0\", New:\"1024\", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, RawConfig:cty.NilVal, RawState:cty.NilVal, RawPlan:cty.NilVal, Meta:map[string]interface {}(nil)}"}
```

### Crossplane Version

1.16.0

### Provider Version

1.6.0

### Additional Info

This issue is not reproducible with MySQL server.

Failed uptest run: https://github.com/crossplane-contrib/provider-upjet-gcp/actions/runs/10254346618
