### ISSUE TITLE
Error with "enable_components" on Cluster resource

### ISSUE THREAD

**Issue by max4t** [crossplane-contrib/provider-upjet-gcp#62]
Hello,

I have the following error:
`observe failed: cannot run refresh: refresh failed: Missing required argument: The argument "enable_components" is required, but no definition was found.`

This is due to the `loggingConfig` which is an array containing `enableComponents`.
When `loggingService` is `none`, `loggingConfig` can be ignored but I believe the api (or the terraform representation) returns something like
```
loggingConfig: [{
    enableComponents: []
}]
```
And if I'm not mistaken, crossplane requires a non-empty value for a property when it's the only one in the object. Meaning, the content returned by the api is not valid (only `loggingConfig: []` would be valid).

It happened on GKE, Crossplane 1.10.1, GCP provider 0.19.0.
And:
```yaml
apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
spec:
  forProvider:
    project: test-error
    location: us-central1-a
    initialNodeCount: 1
    networkingMode: VPC_NATIVE
    networkRef:
      name: base
    subnetworkRef:
      name: cluster-subnet
    loggingService: none
    loggingConfig: []             # with and without this line
    releaseChannel:
      - channel: RAPID
    removeDefaultNodePool: true
    addonsConfig:
      - httpLoadBalancing:
          - disabled: false
    privateClusterConfig:
      - enablePrivateNodes: true
        enablePrivateEndpoint: false
        masterIpv4CidrBlock: 172.16.0.16/28
    ipAllocationPolicy:
      - clusterIpv4CidrBlock: 5.0.0.0/16
        servicesIpv4CidrBlock: 5.1.0.0/16
    defaultSnatStatus:
      - disabled: true
    masterAuthorizedNetworksConfig:
      - cidrBlocks:
          - cidrBlock: 0.0.0.0/0
            displayName: World
```

**Comment by kuisathaverat** [comment]
Using a list and the camel case version of the name also works. The import of some fields terraform objects in lists. The documentation lacks of any example to figure out it.

```yaml
    loggingService: none
    loggingConfig:
      - enableComponents: []
    monitoringConfig:
      - enableComponents: []
        managedPrometheus:
          - enabled: false
```
