### ISSUE TITLE
[Bug]: Import of tag resources failed with 403 error

### ISSUE THREAD

**Issue by nlevee** [crossplane-contrib/provider-upjet-gcp#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

tags.gcp.upbound.io/v1beta1 - TagBinding
tags.gcp.upbound.io/v1beta1 - TagKey
tags.gcp.upbound.io/v1beta1 - TagValue

### Resource MRs required to reproduce the bug

```yaml
apiVersion: tags.gcp.upbound.io/v1beta1
kind: TagKey
metadata:
  annotations:
    meta.upbound.io/example-id: tags/v1beta1/tagkey
    upjet.upbound.io/manual-intervention: "The resource requires a real external name"
    crossplane.io/external-name: "tagKeys/281475435132414"
  labels:
    testing.upbound.io/example-name: key-external
  name: key-external
spec:
  managementPolicies: ["Observe"]
  forProvider: {}
```

### Steps to Reproduce

Create a resource TagKey, TagValue or TagBinding with label `crossplane.io/external-name` and `managementPolicies = ["Observable"]`

### What happened?

Currently, the import fails with at best a 403 error:

![image](https://github.com/user-attachments/assets/76ac7a51-c143-40b1-8f48-c4c66efcf921)

### Crossplane Version

1.17.0

### Provider Version

1.8.1

### Kubernetes Distribution

GKE
