### ISSUE TITLE
[Bug]: displayName is ignored on log-based metric

### ISSUE THREAD

**Issue by shmuelarditi** [crossplane-contrib/provider-upjet-gcp#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

logging.gcp.upbound.io/Metric/v1beta2

### Steps to Reproduce

Can be reproduced by deploying the example, or your own log based metric.

Deploy this:
```
apiVersion: logging.gcp.upbound.io/v1beta2
kind: Metric
metadata:
  annotations:
    meta.upbound.io/example-id: logging/v1beta2/metric
  labels:
    testing.upbound.io/example-name: logging_metric
  name: logging-metric
spec:
  forProvider:
    bucketOptions:
      linearBuckets:
        numFiniteBuckets: 3
        offset: 1
        width: 1
    filter: resource.type=gae_app AND severity>=ERROR
    labelExtractors:
      mass: EXTRACT(jsonPayload.request)
      sku: EXTRACT(jsonPayload.id)
    metricDescriptor:
      displayName: My metric
      labels:
      - description: amount of matter
        key: mass
        valueType: STRING
      - description: Identifying number for item
        key: sku
        valueType: INT64
      metricKind: DELTA
      unit: "1"
      valueType: DISTRIBUTION
    valueExtractor: EXTRACT(jsonPayload.request)
```

### What happened?

When creating the log based metric in GCP, it uses the metadata.name field as the name in the UI
instead of the displayName..

### Crossplane Version

1.17.0

### Provider Version

1.8.3

### Kubernetes Version

v1.30.5

### Kubernetes Distribution

GKE
