### ISSUE TITLE
upbound gcp DatabaseInstance Postgres does not emit root password into written secret

### ISSUE THREAD

**Issue by shanproofpoint** [crossplane-contrib/provider-upjet-gcp#74]
We allocated a :

```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: mydb
spec:
  deletionPolicy: "Delete"
  forProvider:
    deletionProtection: false
    databaseVersion: POSTGRES_13
    region: us-central1
    settings:
      - ipConfiguration:
          - privateNetwork: projects/.../mynetworkvpc
            requireSsl: true
        tier: db-custom-1-3840
        databaseFlags:
          - name: max_connections
            value: "500"
  writeConnectionSecretToRef:
    name: myrootcreds
    namespace: mynamespace
```

verified that it populated the secret with some certs and secrets.
then, when we gave it to :

```
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: mynewdbinstance
spec:
  sslMode: disable
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: mynamespace
      name: myrootcreds
```

and then tried to create a database schema using the provider-sql with:

```
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: mydb
spec:
  providerConfigRef:
    name: mynewdbinstance
  forProvider: {}
```

it fails with 

```
status:
  conditions:
    - lastTransitionTime: '2022-11-19T00:23:33Z'
      message: >-
        observe failed: cannot select database: pq: Could not detect default
        username. Please provide one explicitly
      reason: ReconcileError
      status: 'False'
      type: Synced
```

if you look at the secret it does not contain the password field.

### What environment did it happen in?
Crossplane version: 1.10.1
provider-sql version: crossplane/provider-sql:v0.5.0
upbound gcp version: xpkg.upbound.io/upbound/provider-gcp:v0.18.0

also tried this with provider-sql version: crossplane/provider-sql:v0.6.0 to no avail

**Comment by shanproofpoint** [comment]
> Hello @shanproofpoint, the example manifest you shared belongs to the community [provider-gcp](https://github.com/crossplane-contrib/provider-gcp). If you want to use the official provider-gcp, you can create your instance with a k8s secret reference which points to the password you want to use. You can find an example below:
> 
> ```
> apiVersion: sql.gcp.upbound.io/v1beta1
> kind: DatabaseInstance
> metadata:
>   annotations:
>     meta.upbound.io/example-id: sql/v1beta1/databaseinstance
>   labels:
>     testing.upbound.io/example-name: example_instance
>   # ${Rand...} is not valid YAML and is used with automated testing
>   name: example-instance-ezgi
> spec:
>   forProvider:
>     region: "us-central1"
>     databaseVersion: "MYSQL_5_7"
>     rootPasswordSecretRef:
>       name: psql-password
>       namespace: upbound-system
>       key: password
>     settings:
>       - tier: "db-f1-micro"
>         diskSize: 20
>     deletionProtection: false # allow crossplane to delete the instance automatically
>   writeConnectionSecretToRef:
>     name: example-sql-db-instance-secret
>     namespace: upbound-system
> ---
> apiVersion: v1
> kind: Secret
> metadata:
>   namespace: upbound-system
>   name: psql-password
> data:
>   password: bXlBZG1pblBhc3MxMjM=
> ```
> 
> Once you create an instance like above, your connection secret `example-sql-db-instance-secret` will contain the following fields for the password:
> 
> ```
> attribute.root_password: myAdminPass123
> password: myAdminPass123
> ```
> 
> Please feel free to open a new issue if you encounter any problems.

I sincerely apologize for posting the wrong yaml. please check the updated one. your documentation says for POSTGRES you ignore the secret

**Comment by ezgidemirel** [comment]
No need to apologize :) Could you point to the documentation you mentioned? Because, I could successfully provision a POSTGRES instance with the following manifest: 
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: mydb
spec:
  deletionPolicy: "Delete"
  forProvider:
    deletionProtection: false
    databaseVersion: POSTGRES_13
    region: us-central1
    rootPasswordSecretRef:
      name: psql-password
      namespace: upbound-system
      key: password
    settings:
       - tier: db-custom-1-3840
         databaseFlags:
          - name: max_connections
            value: "500"
  writeConnectionSecretToRef:
    name: myrootcreds
    namespace: upbound-system
```
And I can see the password fields in the `myrootcreds` secret

**Comment by shanproofpoint** [comment]
ah then the documentation can be wrong thank you! i will try this!

**Comment by shanproofpoint** [comment]
https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.20.0/resources/sql.gcp.upbound.io/DatabaseInstance/v1beta1#doc:spec-forProvider-rootPasswordSecretRef

**Comment by shanproofpoint** [comment]
Initial root password. Required for MS SQL Server, ignored by MySQL and PostgreSQL.

**Comment by shanproofpoint** [comment]
it actually does work! however provider-sql was expecting data.endpoint in the secret that now is missing.

**Comment by ezgidemirel** [comment]
Instead of an endpoint, there is a `public_ip_address` field you may use.

**Comment by shanproofpoint** [comment]
understood, also privateIP, however provider-sql does not know that

**Comment by vfarcic** [comment]
@ezgidemirel Are you sure that `rootPasswordSecretRef` works with PostgreSQL? I have a similar situation as @shanproofpoint and, after adding `rootPasswordSecretRef`, the password was indeed added to the secret, but it was not propagated to GCP. I could not access my DB until I manually updated PostgreSQL with the same value as the one Crossplane stored in the secret.

**Comment by ezgidemirel** [comment]
Hello @vfarcic, thanks for mentioning the issue. I didn't try the flow e2e back then and looks like my assumption wasn't correct. We need to create an additional user resource to make it work. You can find the manifest below:
```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Depends on SQL instance to be successfully deleted"
    meta.upbound.io/example-id: sql/v1beta1/user
  labels:
    testing.upbound.io/example-name: example_user
  name: example-user
spec:
  forProvider:
    passwordSecretRef:
      name: psql-password
      namespace: upbound-system
      key: password
      instanceRef:
        name: mydb
```

@shanproofpoint as you mentioned, provider-sql requires `endpoint` field to work. Therefore, I ended up using [provider-kubernetes](https://github.com/crossplane-contrib/provider-kubernetes/) for updating `myrootcreds` secret and added `publicIP` as `endpoint` and `username` `password` fields. 

In below, you can find all the manifests I created:

```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: mydb
  labels:
    testing.upbound.io/example-name: example_instance
spec:
  deletionPolicy: "Delete"
  forProvider:
    deletionProtection: false
    databaseVersion: POSTGRES_13
    region: us-central1
    settings:
       - tier: db-custom-1-3840
         databaseFlags:
          - name: max_connections
            value: "500"
  writeConnectionSecretToRef:
    name: myrootcreds
    namespace: upbound-system

---

apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Depends on SQL instance to be successfully deleted"
    meta.upbound.io/example-id: sql/v1beta1/user
  labels:
    testing.upbound.io/example-name: example_user
  name: example-user
spec:
  forProvider:
    passwordSecretRef:
      name: psql-password
      namespace: upbound-system
      key: password
    instanceRef:
      name: mydb

--- 

# Make sure provider-kubernetes has enough permissions to install your objects into cluster
#
# You can give admin permissions by running:
# SA=$(kubectl -n crossplane-system get sa -o name | grep provider-kubernetes | sed -e 's|serviceaccount\/|crossplane-system:|g')
# kubectl create clusterrolebinding provider-kubernetes-admin-binding --clusterrole cluster-admin --serviceaccount="${SA}"
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    source: InjectedIdentity

---

apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
spec:
  references:
  - patchesFrom:
      apiVersion: sql.gcp.upbound.io/v1beta1
      kind: User
      name: example-user
      namespace: upbound-system
      fieldPath: metadata.name
    toFieldPath: stringData.username
  - patchesFrom:
      apiVersion: v1
      kind: Secret
      name: psql-password
      namespace: upbound-system
      fieldPath: data.password
    toFieldPath: data.password
  - patchesFrom:
      apiVersion: v1
      kind: Secret
      name: myrootcreds
      namespace: upbound-system
      fieldPath: data.publicIP
    toFieldPath: data.endpoint
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        name: myrootcreds
        namespace: upbound-system
  providerConfigRef:
    name: kubernetes-provider

--- 

apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: mynewdbinstance
spec:
  sslMode: disable
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: upbound-system
      name: myrootcreds

---

apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: mydb
spec:
  providerConfigRef:
    name: mynewdbinstance
  forProvider: {}

```
