### ISSUE TITLE
[Bug]: `ProjectDefaultServiceAccounts` resource in perpetual UpdatedExternalResource with no action made in GCP

### ISSUE THREAD

**Issue by zurzolop** [crossplane-contrib/provider-upjet-gcp#748]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

cloudplatform.gcp.upbound.io/v1beta1 - ProjectDefaultServiceAccounts

### Resource MRs required to reproduce the bug

**_providers.yaml_**
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-cloudplatform
spec:
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/upbound/provider-gcp-cloudplatform:v1.11.0
  packagePullPolicy: IfNotPresent
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: project-runtime-config
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-gcp
spec:
  package: xpkg.upbound.io/upbound/provider-family-gcp:v1.11.0
  packagePullPolicy: IfNotPresent
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: default
```

**_deployment-runtime-config.yaml_**
```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: project-runtime-config
spec:
  deploymentTemplate:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: REDACTED@REDACTED.iam.gserviceaccount.com
    spec:
      selector:
        matchLabels:
          pkg.crossplane.io/provider: provider-gcp-cloudplatform
      template:
        metadata:
          annotations:
            iam.gke.io/gcp-service-account: REDACTED@REDACTED.iam.gserviceaccount.com
          labels:
            pkg.crossplane.io/provider: provider-gcp-cloudplatform
        spec:
          containers:
          - name: package-runtime
  serviceAccountTemplate:
    metadata:
      name: crossplane-workload-identity
```

**_provider-config.yaml_**
```
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: workload-id-providerconfig
spec:
  credentials:
    impersonateServiceAccount:
      name: REDACTED@REDACTED.iam.gserviceaccount.com
    source: ImpersonateServiceAccount
  projectID: REDACTED
```

**_disable.yaml_**
```
apiVersion: "cloudplatform.gcp.upbound.io/v1beta1"
kind: "ProjectDefaultServiceAccounts"
metadata:
  name: "test-disable-default-service-accounts"
spec:
  forProvider:
    action: "DISABLE"
    project: "REDACTED"
  providerConfigRef:
    name: "workload-id-providerconfig"
```

### Steps to Reproduce

Apply manifests in order as above

### What happened?

Apply of `ProjectDefaultServiceAccounts` resource in `disable.yaml` shows as created, and shortly after shows SYNCED and READY as both `True`, however when describing the resource the only events present show a recurrence of:
```
Events:
  Type    Reason                   Age                    From                                                                              Message
  ----    ------                   ----                   ----                                                                              -------
  Normal  UpdatedExternalResource  54s (x14467 over 35m)  managed/cloudplatform.gcp.upbound.io/v1beta1, kind=projectdefaultserviceaccounts  Successfully requested update of external resource
```

I don't see any notable messages in provider pod logs, nor any log events in GCP in either the cluster project or target project referenced in the `disable.yaml` file.

### Relevant Error Output Snippet

```shell
see above
```

### Crossplane Version

v1.18.1

### Provider Version

v1.11.0

### Kubernetes Distribution

GKE

### Additional Info
I have tried all [support values](https://marketplace.upbound.io/providers/upbound/provider-gcp-cloudplatform/v1.11.4/resources/cloudplatform.gcp.upbound.io/ProjectDefaultServiceAccounts/v1beta1#doc:spec-forProvider-action) for `Action:` in the spec, and have tried to create this resource both within a composition and standalone.
