### ISSUE TITLE
upbound gcp compute Instance .status does not show resulting private ip after provisioning

### ISSUE THREAD

**Issue by shanproofpoint** [crossplane-contrib/provider-upjet-gcp#76]
### What happened?

created a vm with : https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.20.0/resources/compute.gcp.upbound.io/Instance/v1beta

using :
```
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: CLOWN_NAME_X
spec:
  forProvider:
    bootDisk:
      - initializeParams:
          #- image: debian-cloud/debian-11
          - image: GCP_IMAGE_ID_X
    machineType: f1-micro
    networkInterface:
      - subnetwork: VPC_REGIONAL_SUBNET_X
        #for public ip address include the following section XD
        #accessConfig:
        #  - networkTier: PREMIUM
    zone: FIRST_ZONE_X
    tags:
      - pfpt-clowns
    metadata:
      enable-oslogin: "true"
    project: PROJECT_ID_X
```

expecting the status field to have all of the ip information but it does not show any:

```
  status:
    atProvider:
      bootDisk:
      - diskEncryptionKeySha256: ""
      cpuPlatform: Intel Broadwell
      currentStatus: RUNNING
      id: projects/mynetwork/zones/europe-west3-a/instances/clown4-private
      instanceId: "123"
      labelFingerprint: ----
      metadataFingerprint: -----
      networkInterface:
      - ipv6AccessType: ""
        name: nic0
      selfLink: https://www.googleapis.com/compute/v1/----
      tagsFingerprint: ----
    conditions:
    - lastTransitionTime: "2022-12-08T23:03:04Z"
      reason: Available
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-12-08T23:02:44Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2022-12-08T23:03:00Z"
      reason: Finished
      status: "True"
      type: AsyncOperation
    - lastTransitionTime: "2022-12-08T23:03:00Z"
      reason: Success
      status: "True"
      type: LastAsyncOperation

```

using gcloud describe shows the ip info
i really dont want to lug in another provider to read it... seems overkill and complex..

### How can we reproduce it?
straight forward apply something similar to above.

### What environment did it happen in?

* Universal Crossplane Version: 1.10.1
* Provider Version: xpkg.upbound.io/upbound/provider-gcp:v0.18.0
