### ISSUE TITLE
[Bug]: Documentation for `ServiceAccountIAMMember` could be made clearer regarding how to reference the service account

### ISSUE THREAD

**Issue by mattwelke** [crossplane-contrib/provider-upjet-gcp#760]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

Trying the cloudplatform GCP provider today. Spent a while debugging only to realize I wasn't using the correct syntax for the provider.

The docs at https://marketplace.upbound.io/providers/upbound/provider-gcp-cloudplatform/v1.12.0/resources/cloudplatform.gcp.upbound.io/ServiceAccountIAMMember/v1beta2 mention three fields that sounded like I could use them for referencing the service account:

- serviceAccountId
- serviceAccountIdRef
- serviceAccountIdSelector

I ignored "selector" because I'm not using labels for selecting other resources. I've seen other providers include fields that end in "selector" so I was familiar with the pattern and that I could expect another field to exist that I could use to just target the one resource I had in mind. I tried "serviceAccountId" because "ref" sounded like something more complex that I wouldn't need. It didn't work though. The kube API server accepted it but I would get errors reported in the events like:

```
errors:

5m13s       Warning   CannotCreateExternalResource             serviceaccountiammember/workload-identity-binding                      async create failed: failed to create the resource: [{0 Error retrieving IAM policy for service account 'GCP_SA_NAME@PROJECT_ID.iam.gserviceaccount.com': googleapi: got HTTP response code 404 with body: <!DOCTYPE html>...
```

The full error message with that HTML included a malformed URL where it looked like an empty string was inserted into a GCP URL.

I tried different variations of strings to get it to work but had no luck.

I eventually used a GitHub code search to find examples of people using `ServiceAccountIAMMember` and saw an example where someone used "serviceAccountIdRef" instead. That's when I realized all I had to do was use that and then put in the name of the service account.

I think the docs could be made clearer if they excluded the field I used which doesn't seem to be used at all. Also, though this would probably apply to all providers, explanations in the docs of when one should use ref and when one should use selector (though it appears the docs are generated from Terraform providers that this project may not control so I can see that being tricky). Also, an example using ref.

### Steps to Reproduce

See above.

### What happened?

See above.

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

1.19.0

### Provider Version

1.12.0

### Kubernetes Version

1.31

### Kubernetes Distribution

GKE

**Comment by mike-sirs** [comment]
For anyone who find it in the future, this is how `serviceAccountId` value expected
`serviceAccountId: projects/YOUR_GCP_PROJECT/serviceAccounts/SA_NAME@YOUR_GCP_PROJECT.iam.gserviceaccount.com`

crossplane resources like https://marketplace.upbound.io/providers/upbound/provider-gcp-cloudplatform/v2.0.1/resources/cloudplatform.gcp.m.upbound.io/Folder/v1beta1 missing examples, having something like
```
apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: workload-identity
spec:
  forProvider:
    member: serviceAccount:YOUR_GCP_PROJECT.svc.id.goog[NS/SERVICE_ACCOUNT]
    role: roles/iam.workloadIdentityUser
    serviceAccountId: projects/YOUR_GCP_PROJECT/serviceAccounts/SA_NAME@YOUR_GCP_PROJECT.iam.gserviceaccount.com
```
for example like tofu/terraform documentation does it
