### ISSUE TITLE
[Request]: Way to reference `TargetHTTPSProxy` from `GlobalForwardingRule` using `targetRef`

### ISSUE THREAD

**Issue by mattwelke** [crossplane-contrib/provider-upjet-gcp#763]
### What problem are you facing?

I'm setting up a load balancer. I'm creating Crossplane YAML based on the steps I completed using `gcloud` while following https://cloud.google.com/load-balancing/docs/https/setting-up-https-serverless.

My `TargetHTTPSProxy` looks like the following. I confirmed that it was able to be synced and reach ready.

```yaml
apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetHTTPSProxy
metadata:
  name: ${APP_NAME}-target-https-proxy
spec:
  forProvider:
    urlMap: ${APP_NAME}-url-map
    sslCertificates:
      - ${APP_NAME}-cert
```

I found while configuring the `GlobalForwardingRule` that I could not YAML like the following.

```yaml
apiVersion: compute.gcp.upbound.io/v1beta2
kind: GlobalForwardingRule
metadata:
  name: ${APP_NAME}-forwarding-rule
spec:
  forProvider:
    ipAddressRef:
      name: ${ADDRESS}
    ipProtocol: TCP
    portRange: "443"
    targetRef:
      name: ${APP_NAME}-target-https-proxy
```

When I did, I got the error `'cannot resolve references: mg.Spec.ForProvider.Target: cannot get referenced resource: TargetSSLProxy.compute.gcp.upbound.io "subscriber-app-target-https-proxy" not found'`.

Instead, I had to write it like the following, using the raw URL (the selfLink of the referenced resource).

```yaml
apiVersion: compute.gcp.upbound.io/v1beta2
kind: GlobalForwardingRule
metadata:
  name: ${APP_NAME}-forwarding-rule
spec:
  forProvider:
    ipAddressRef:
      name: ${ADDRESS}
    ipProtocol: TCP
    portRange: "443"
    target: https://www.googleapis.com/compute/v1/projects/${PROJECT_ID}/global/targetHttpsProxies/${APP_NAME}-target-https-proxy
```

I confirmed it was then synced and reach ready.

I think the issue here is that `GlobalForwardingRule` can only reference objects of the type `TargetSSLProxy`. Even though you can also reference objects of type `TargetHTTPSProxy` (and GCP [docs](https://cloud.google.com/load-balancing/docs/target-proxies) state that that's what you'd do when setting up a Classic Application Load Balancer or a Global external Application Load balancer), the provider right now doesn't support targeting them this way.

### What could help solve your problem?

Support for `GlobalForwardingRule` to use `targetRef` to target all types of valid targets.

#### Why it would help me

The "ref" technique is more convenient than specifying the full self-link. It's also less error prone (Google could change the format of the links in the future). It's also my understanding that using the referencing features allows Crossplane to manage your resources more intelligently (order of creation/deletion etc). So I think having ref support here would be useful.
