### ISSUE TITLE
[Bug]: Potential Memory Leak in provider-gcp-secretmanager – Continuous Increase in RAM Usage

### ISSUE THREAD

**Issue by mcortinas** [crossplane-contrib/provider-upjet-gcp#765]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

* secretmanager.gcp.upbound.io/v1beta2 - SecretIAMMember

### Resource MRs required to reproduce the bug

181 SecetIAMember like this one managed by our provider 
```
apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: SecretIAMMember
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-03-31T13:55:07Z"
    crossplane.io/external-create-succeeded: "2025-03-31T13:55:07Z"
    crossplane.io/external-name: XXX
  name: kong-suppliers-api-key-hotels-bb
spec:
  deletionPolicy: Delete
  forProvider:
    member: principal://iam.googleapis.com/projects/X/locations/global/workloadIdentityPools/GCP_PROJECT.svc.id.goog/subject/ns/someNAMESPACE/sa/someSERVCEACCOUNT
    project: GCP_PROJECT
    role: roles/secretmanager.secretAccessor
    secretId: somesecretId
  managementPolicies:
  - '*'
  providerConfigRef:
    name: gcp-GCP_PROJECT

```

### Steps to Reproduce

Steps to Reproduce:
1. Deploy Crossplane in a GKE cluster running Kubernetes v1.32.2-gke.1182001.
2. Install the provider-gcp-secretmanager provider v1.12.1 and ensure it is properly configured.
3. Create and manage at least 181 SecretIAMMember objects.
4. Monitor the memory usage of the provider-gcp-secretmanager pod using Grafana or kubectl top pods.
5. Observe that the memory consumption gradually increases over time without stabilizing.
6. Restart the pod and verify that the memory growth pattern continues after some time.

### What happened?

We have observed a continuous increase in memory consumption in the provider-gcp-secretmanager pod. The memory usage gradually increases over time without stabilizing, as shown in the attached Grafana graph.

Grafana Monitoring:

The provider-gcp-secretmanager pod's memory usage steadily increases, currently exceeding 2.5 GiB.

![Image](https://github.com/user-attachments/assets/95ff0dac-e4e1-40e6-82a3-55949cdfe16e)

Other providers (e.g., provider-gcp-dns, provider-family-gcp) exhibit more stable memory usage.

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

v1.18.0

### Provider Version

v1.12.1

### Kubernetes Version

v1.32.2-gke.1182001

### Kubernetes Distribution

GKE

### Additional Info

This behavior is concerning because a similar issue was reported in [#538](https://github.com/crossplane-contrib/provider-upjet-gcp/issues/538). If this is a general problem affecting multiple Upjet-based providers, it could have a serious impact on stability and resource utilization.
