### ISSUE TITLE
[Bug]: `ManagedSSLCertificate` reports SYNCED:False even though it was able to be synced

### ISSUE THREAD

**Issue by mattwelke** [crossplane-contrib/provider-upjet-gcp#766]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

If I create a `ManagedSSLCertificate`, it will report as not synced even though the resource is created in GCP (visible in the GCP UI).

E.g.

```
apiVersion: compute.gcp.upbound.io/v1beta2
kind: ManagedSSLCertificate
metadata:
  name: message-processor-app
spec:
  forProvider:
    managed:
      domains:
        - <redacted>
```

```
$ kubectl get managedsslcertificate message-processor-app
NAME                    SYNCED   READY   EXTERNAL-NAME           AGE
message-processor-app   False    True    message-processor-app   5m23s
```

I notice that there are conditions being set that describe updates failing. I'm wondering if this might be related to Crossplane reporting it as not yet successfully synced.

This is what those look like:

```
  conditions:
  - lastTransitionTime: "2025-04-08T01:58:40Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-04-08T01:58:41Z"
    message: 'update failed: async update failed: failed to update the resource: [{0
      doesn''t support update  []}]'
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2025-04-08T01:58:41Z"
    message: 'async update failed: failed to update the resource: [{0 doesn''t support
      update  []}]'
    reason: AsyncUpdateFailure
    status: "False"
    type: LastAsyncOperation
```

### Steps to Reproduce

see above

### What happened?

see above

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

1.19.0

### Provider Version

1.12.0

### Kubernetes Version

1.31

### Kubernetes Distribution

GKE
