### ISSUE TITLE
`connectionDetails` is not working

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/provider-upjet-gcp#77]
### What happened?

I rewrote one of my compositions to use the official GCP provider. Everything seems to be working except `    connectionDetails`. 

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: google-postgresql-official
  labels:
    provider: google-official
    db: postgresql
spec:
  ...
  resources:
  - name: sql
    base:
      apiVersion: sql.gcp.upbound.io/v1beta1
      kind: DatabaseInstance
      spec:
        ...
    connectionDetails:
    - type: FromValue
      name: username
      value: postgres
    - fromConnectionSecretKey: password
    - fromConnectionSecretKey: publicIP
      name: endpoint
    - type: FromValue
      name: port
      value: "5432"
```

The full source code is in https://github.com/vfarcic/devops-toolkit-crossplane/blob/master/packages/sql/gcp-official.yaml#L171.

The secret does not contain any of the fields specified in `connectionDetails`. One of the other hand, almost identical Composition based on the "other" GCP provider works (https://github.com/vfarcic/devops-toolkit-crossplane/blob/master/packages/sql/gcp.yaml#L171). 

### How can we reproduce it?

Full instructions how to reproduce it are in https://github.com/vfarcic/devops-toolkit-crossplane/blob/master/packages/sql/gcp.md.

After the DB instance is created, check the fields in the secret `my-db` located in the Namespace `infra`.
