### ISSUE TITLE
[Bug]: secret generated from writeConnectionSecretToRef on gcp cluster MR has empty user token in kubeconfig

### ISSUE THREAD

**Issue by rahulrayal** [crossplane-contrib/provider-upjet-gcp#777]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

container.gcp.upbound.io/v1beta2 - Cluster

### Resource MRs required to reproduce the bug

```
apiVersion: container.gcp.upbound.io/v1beta2
kind: Cluster
metadata:
  name: test-cluster
spec:
  providerConfigRef:
    name: test-provider-config
  forProvider:
    deletionProtection: false
    location: test-location
    removeDefaultNodePool: true
    enableAutopilot: false
    initialNodeCount: 1
  writeConnectionSecretToRef:
    name: test-secret
    namespace: test-namespace
```

### Steps to Reproduce

You can apply the above MR manifest and after the creation of the cluster is successful you can check the kubeconfig in the test-secret of test-namespace

### What happened?

While using the field writeConnectionSecretToRef in the Cluster (v1beta2) MR of upbound/provider-gcp-container@v1.12.0. We have observed that the kubeconfig added in the secret created by writeConnectionSecretToRef has empty user token

```
users:
- name: test-cluster
  user: {}
```

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

v1.19.0

### Provider Version

v1.12.0

### Kubernetes Version

Client Version: v1.32.3 Kustomize Version: v5.5.0 Server Version: v1.32.2-eks-bc803b4

**Comment by rahulrayal** [comment]
is there any update on this?

**Comment by kostyaplis** [comment]
I think this is expected behavior: unless you set `issueClientCertificate: true` the `master_auth.0.client_certificate` and `master_auth.0.client_key` fields remain empty.
```yaml
masterAuth:
  clientCertificateConfig:
    issueClientCertificate: true
```
However, even when it is set, the `client` user has no permissions in the GKE cluster, so it’s effectively useless for automation — not to mention that the `masterAuth` approach is generally discouraged.

I found some [configuration examples](https://github.com/upbound/configuration-gcp-gke/blob/main/apis/composition.yaml#L283-L296) suggesting to use generated kubeconfig in the `credentials` section and a reference to SA private_key in the `identity` section. The following MR snippet works, although the use of long-lived credentials is typically discouraged as well.

```yaml
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: my-sa-with-required-iam-permissions-to-manage-cluster-api-objects
spec:
  forProvider:
    serviceAccountId: "my-sa-email@my-projectID.iam.gserviceaccount.com"
  writeConnectionSecretToRef:
    name: {{ my SA secret name }}
    namespace: {{ my secret namespace }}

---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubeconfig-remote
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ my secret namespace }}
      name: {{ my secret name }} # Points to the secret created by the GKE cluster
      key: kubeconfig
  identity:
    source: Secret
    type: GoogleApplicationCredentials
    secretRef:
      namespace: {{ my secret namespace }}
      name: {{ my SA secret name }}
      key: private_key
```

Looking at the [kubernetes provider code](https://github.com/crossplane-contrib/provider-kubernetes/blob/f552b2446dfe9dd88a83a8fa916f1f60e9f4b05e/pkg/kube/config/config.go#L42C46-L42C62), it seems that `source: InjectedIdentity` is also supported. So, if you have Workload Identity configured and your Crossplane SA has permission to manage the target cluster objects, the following provider config works and utilizes identity tokens instead of long-lived creds:

```yaml
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubeconfig-remote
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ my secret namespace }}
      name: {{ my secret name }} # Points to the secret created by the GKE cluster
      key: kubeconfig
  identity:
    type: GoogleApplicationCredentials
    source: InjectedIdentity
```

It seems that the only thing that above provider config lacks is an `ImpersonateServiceAccount` source, which you might expect to need when managing clusters created in different projects. However, I believe that relates to limitations in the `provider-kubernetes` implementation (please correct me if I'm wrong).
