### ISSUE TITLE
[Bug]: using the `keepers` field for `ServiceAccountKey` is not working as expected

### ISSUE THREAD

**Issue by bd3lage** [crossplane-contrib/provider-upjet-gcp#793]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Resource(s)

cloudplatform.gcp.upbound.io/v1beta1 - ServiceAccountKey

### Resource MRs required to reproduce the bug

```
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: test-sa-rotation-key
spec:
  deletionPolicy: Delete
  forProvider:
    keepers:
      rotation: "1"
    publicKeyType: TYPE_X509_PEM_FILE
    serviceAccountIdRef:
      name: test-sa-rotation
  writeConnectionSecretToRef:
    name: test-sa-rotation-secret
    namespace: test
```

### Steps to Reproduce

Apply manifest from above, then update the `spec.forProvider.keepers.rotation` value and apply again.

### What happened?

Using the `keepers` field from https://marketplace.upbound.io/providers/upbound/provider-gcp-cloudplatform/v1.13.0/resources/cloudplatform.gcp.upbound.io/ServiceAccountKey/v1beta1#doc:spec-forProvider-keepers

I expect that if I update the value in `keepers` it will replace the key. 

Instead, I get 
```
  Warning  CannotUpdateExternalResource     1s (x12 over 23s)  managed/cloudplatform.gcp.upbound.io/v1beta1,
 kind=serviceaccountkey  async update failed: refuse to update the external resource because the following 
update requires replacing it: cannot change the value of the argument "keepers.rotation" from "1" to "2"
```

### Relevant Error Output Snippet

```shell

```

### Crossplane Version

1.16.0

### Provider Version

1.13.0
