### ISSUE TITLE
cloud sql user manual-intervention "Depends on SQL instance to be successfully deleted"

### ISSUE THREAD

**Issue by gberche-orange** [crossplane-contrib/provider-upjet-gcp#85]
As suggested into 

https://github.com/upbound/upjet/blob/main/docs/add-new-resource-short.md mentions
> There are cases where the resource requires user to take an action that is not possible with a Crossplane provider or automated testing tool. In such cases, we should leave the actions to be taken as annotation on the resource like the following:
>  annotations:
>     upjet.upbound.io/manual-intervention: "User needs to upload a authorization script and give its path in spec.forProvider.filePath"
> 
> An issue in the official-providers repo explaining the situation [should be opened](https://github.com/upbound/official-providers/issues/new/choose) preferably with the example manifests (and any resource configuration) already tried.

### What happened?

The CloudSql User can not be deleted unless the DatabaseInstance was deleted first:

https://github.com/upbound/provider-gcp/blob/090f08482cf66c04771bbcf4d983c4138e97d234/examples/sql/user.yaml#L4-L5

```yaml
status:
  atProvider:
    id: default//kuttl-medium-mysql-instance-w6qpx-zv8tz
  conditions:
  - lastTransitionTime: "2022-12-16T16:27:20Z"
    message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource google_sql_user.kuttl-medium-mysql-instance-w6qpx-pr9tl has lifecycle.prevent_destroy
      set, but the plan calls for this resource to be destroyed. To avoid this error
      and continue with the plan, either disable lifecycle.prevent_destroy or reduce
      the scope of the plan using the -target flag.'
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2022-12-16T16:25:34Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-12-16T16:24:47Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
  - lastTransitionTime: "2022-12-16T16:24:47Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
```

### How can we reproduce it?

https://github.com/upbound/platform-ref-gcp/blob/ecd7de576e9da710360e17952b2c3cfd1be851c9/package/database/postgres/composition.yaml#L37-L52

### Workaround

Imperative workaround:

https://github.com/upbound/platform-ref-gcp/blob/ecd7de576e9da710360e17952b2c3cfd1be851c9/examples/testhooks/delete-sql-user.sh#L4-L7
>  Delete the sql user before deleting the database not to orphan the user object
> Use explicit ordering of the sql resources to avoid database stuck
> Note(turkenh): This is a workaround for the infamous dependency problem during deletion.
> ${KUBECTL} delete user.sql.gcp.upbound.io --all

Declarative workaround:
* a Kyverno Policy could enforce a specific deletion order for the MRs,

@bobh66 is preparing a write up for this, see https://crossplane.slack.com/archives/CEG3T90A1/p1671041047666789?thread_ts=1671039517.972969&cid=CEG3T90A1

* https://github.com/crossplane/crossplane/issues/3393

### What environment did it happen in?

* Universal Crossplane Version:
* Provider Version:
