### ISSUE TITLE
sql: `User` CRD should fail fast on invalid passwordSecretRef

### ISSUE THREAD

**Issue by gberche-orange** [crossplane-contrib/provider-upjet-gcp#87]
### What happened?

Given a passwordSecretRef referencing a non existing secret
When User reconciles
It silently sets an empty password without reflecting any error in the CRD status nor in the provider logs

Sample provider log:
```
1.6715338598788996e+09    DEBUG    provider-gcp    External resource is up to date    {"controller": "managed/sql.gcp.upbound.io/v1beta1, kind=user", "request": "/kuttl-medium-mysql-instance-w6qpx-pr9tl", "uid": "af071a1a-82f4-427d-a337-64fcd44cdcdb", "version": "103110491", "external-name": "app", "requeue-after": 1671534459.878897}
```                       

Sample User CR status:
```
  NAME                                                              READY   SYNCED   EXTERNAL-NAME   AGE
  user.sql.gcp.upbound.io/kuttl-medium-mysql-instance-w6qpx-pr9tl   True    True     app             22h

  status:
  atProvider:
  id: app/%/kuttl-medium-mysql-instance-w6qpx-zv8tz
  conditions:
  - lastTransitionTime: "2022-12-19T12:08:52Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-12-19T12:07:32Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2022-12-19T12:08:04Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
  - lastTransitionTime: "2022-12-19T12:08:04Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
``` 

### How can we reproduce it?

Set an invalid passwordSecretRef pointing to a non existant secret

https://github.com/upbound/provider-gcp/blob/e0252bbec3e86726f82df44ffb91df9c6fcb7076/examples/sql/user.yaml#L10-L15

### What environment did it happen in?

* Universal Crossplane Version: `image: crossplane/crossplane:v1.10.1`
* Provider Version: [v0.20.0](https://github.com/upbound/provider-gcp/releases/tag/v0.20.0)
