### ISSUE TITLE
gcp: Support  BucketObject 'source' type fields (file path references)

### ISSUE THREAD

**Issue by donovanmuller** [crossplane-contrib/provider-upjet-gcp#9]
### What problem are you facing?

Provider Name: `provider-gcp`
Provider Version: development

https://github.com/upbound/official-providers/blob/cba2980241265105e38d027b79b7486a69abb31b/provider-gcp/examples-generated/storage/bucketobject.yaml#L13

GCP `BucketObject` resource contains two fields that represent the actual data to upload into a `Bucket`:

* `content`: String value uploaded as-is. This works as expected
* `source`: A reference to a _file path_, whose contents are uploaded. This is currently not supported

The `source` field is currently generated as a `string`. https://github.com/upbound/official-providers/blob/cba2980241265105e38d027b79b7486a69abb31b/provider-gcp/package/crds/storage.gcp.upbound.io_bucketobjects.yaml#L236-L240 However, this value cannot contain an actual file path, as it would be relative to the Terraform workspace in the provider environment. Marking the field as `sensitive: true` will generate a `sourceSecretRef`, however, this will also not work, since the provider implementation only accepts a [file path](https://github.com/hashicorp/terraform-provider-google/blob/80f6dd2fcc1c209ed2b066d9b758db2e34145368/google/resource_storage_bucket_object.go#L279-L284) and not actual file content encoded into a Secret.

### How could Official Providers help solve your problem?

Allow the `source` field to reference a `Secret` with encoded file content and make a file path available to the underlying Terraform provide, which will have that file path set in the `source` field in `main.tf.json`. To support an example like below:

```yaml
apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketObject
metadata:
  labels:
    testing.upbound.io/example-name: bucket-object
  name: bucket-object
spec:
  forProvider:
    bucketSelector: 
      matchLabels:
        testing.upbound.io/example-name: bucket-object
    name: bucket-object
    sourceSecretRef:
      name: bucket-object
      namespace: upbound-system
      key: upbound.txt
    contentType: text/plain

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: bucket-object
  name: bucket-object-34234
spec:
  forProvider:
    location: US
    storageClass: MULTI_REGIONAL
    
---

apiVersion: v1
kind: Secret
metadata:
  labels:
    testing.upbound.io/example-name: bucket-object
  name: bucket-object
  namespace: upbound-system
data:
  upbound.txt: VlhCaWIzVnVaQW89Cg==
```
